### PR TITLE
Fix link to IdentityServer4 samples

### LINKED ISSUE #53: Broken links to IdentityServer4.Samples repo
The templates that include a home page view link to IdentityServer4.Samples repo which does not exist.

### PR DESCRIPTION
**Pull request by amiller-ims**
Fixes #53

### CODE REVIEW

**Comment by brockallen** [comment]
great, thanks!

**Comment by brockallen** [comment]
we need the same fix in the main repo. mind doing the same PR there?

**Comment by amiller-ims** [comment]
Such as
https://github.com/IdentityServer/IdentityServer4/blob/master/src/AspNetIdentity/host/Views/Home/Index.cshtml
 ?

I don't mind.

**Comment by brockallen** [comment]
Yes, for the two ones that actually are the code we use for these templates: 

https://github.com/IdentityServer/IdentityServer4/tree/master/src/IdentityServer4/host

and

https://github.com/IdentityServer/IdentityServer4/tree/master/src/AspNetIdentity/host

Great, thanks!

**Pull request merged**
