### PR TITLE
Make ASP.NET Identity template more idiomatic

### PR DESCRIPTION
**Pull request by leastprivilege**

### CODE REVIEW

**Comment by brockallen** [comment]
Why? I thought we said that was not our job to look like the VS templates?

**Comment by leastprivilege** [comment]
did you actually look at the changes?

**Comment by brockallen** [comment]
Yes. Are `IdentityConstants` the ones from the templates?

**Comment by scottbrady91** [comment]
no: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IdentityConstants.cs

**Pull request merged**
