### PR TITLE
Co-enable SQL Server and SQLite Identity/Autogenerate field annotations

### PR DESCRIPTION
**Pull request by tomgron**
As described in EF Core documentation here : https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers#one-migration-set

Note : haven't tested this by creating new items with the templates yet. Just stumbled to this after trying to switch from default SQLite implementation to SQL Server.

### CODE REVIEW

**Comment by tomgron** [comment]
Apparently AdminUI's migration SQL scripts with files ConfigurationDb.sql and PersistedGrantDb.sql are out-of-sync with IdentityServer4 with Entity Framework Stores template and generate errors after switching provider to SQL Server.

**Comment by tomgron** [comment]
Maybe better option would be creating the tables (and insertions) with code-first as the SQL dialect seems to differ quite a bit between SQL Server and SQLite implementations.

**Comment by scottbrady91** [comment]
Hi! AdminUI community edition is limited to SQLite, so changes to that template would need to be removed from the PR.

**Comment by tomgron** [comment]
Ok - will update PR in a minute

**Comment by tomgron** [comment]
Ok - reset the AdminUI template to origin

**Pull request closed without merging**
