### PR TITLE
Update to resolve IdentityServer4 AdminUI error when logging in using base template

### PR DESCRIPTION
**Pull request by djengineerllc**
There was a mismatch between Identity and IdentityExpress.  I updated the code to use IdentityExpress.  Now the /Account/Login is working again and not throwing a weird error.

It fixes this error from here: https://github.com/IdentityServer/IdentityServer4.Templates/issues/50

I don't think whoever put this in described the error properly.  I started up a base template implementation of the is4admin using "sudo dotnet new is4admin".  Perform "sudo dotnet build" and then "sudo dotnet run".  Then use the admin http://localhost:5000/admin to create a user with a password.  Then go to http://localhost:5000 and login with the newly created user.  You get the exact error from the above issue#50.

After making the update, the issue was resolved and I could properly log in with the newly created user.

### CODE REVIEW

**Comment by djengineerllc** [comment]
Not sure what that error is: Failed to install cake
From Portal, I know that the cake is a lie.
Let me know if there is something in my request that is failing the build, or if there is an error in the build pipeline.  It is running and working for me, but I'm using dotnet core 3 on Ubuntu 19.04.

**Comment by djengineerllc** [comment]
From the last 2 builds in the build history on the Azure pipeline for the Templates, it looks like they are both failing with the same build error.  This appears to be a build pipeline issue to me.

Here's the build error:

A compatible SDK version for global.json version: [3.0.100-preview9-014004] from [D:\a\1\s\global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Failed to install cake
##[error]PowerShell exited with code '1'.

**Comment by djengineerllc** [comment]
I'm thinking that after this update -> https://github.com/IdentityServer/IdentityServer4.Templates/commit/4161c5346b16c62f778789e7e69c40798464f3a4

the global.json updated (2 days ago) which corresponds to the build that failed 2 days ago and this build that failed.

I think the commit from 2 days ago is good, since I am also using "3.0.100-preview9-014004".  I think it is just the Azure pipeline build.

**Comment by leastprivilege** [comment]
@scottbrady91

**Comment by scottbrady91** [comment]
AdminUI does work with `IdentityDbContext`, so I'm surprised that this is solving issues.

Happy to merge in though.

**Comment by leastprivilege** [comment]
I'd appreciate a bit more confidence before I merge external code @scottbrady91 ...

**Pull request closed without merging**
